# Top-level site settings
baseurl = "https://lamendo.la"
builddrafts = false
author = "Salvatore LaMendola"
languageCode = "en-us"
title = "Sitevatore"
theme = "cocoavatore"
disablePathToLower = true
pygmentsuseclasses = true

[permalinks]
  blog = "blog/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[params]
  #twitter = "https://twitter.com/yourtwitterusername"
  include_rss = true           # include RSS <link> tag in <head> and show RSS icon
  latestpostscount = 5              # how many posts to display on the home page
  i18n_flags = false # whether to display small country flags for available translations
  author = "SALVATORE LAMENDOLA (vt0r)"
  cachebuster = false # add the current unix timestamp in query string for cache busting css assets
  dateform = "Jan 2, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 MST"
  #description = ""
  email = "salvatore[at@@]lamendo[dot..]la"
  #extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.
  faviconfile = "images/favicon.ico"
  github = "https://github.com/vt0r"
  #instagram = "//instagram.com/you"
  #px500 = "//500px.com/username"
  lang = "en"
  linkedin = "https://www.linkedin.com/in/salvatorelamendola"
  keyoxide = "https://keyoxide.org/4b5fd875f30c8cf39191b11dead217668b7336d5"
  mastodon = "https://noc.social/@vt0r"
  noshowreadtime = false # if true, don't show "<x> minutes read" in posts
  selfintro = "" # appears in the site header when set to a non-empty string
  avatar = "images/avatar@2x.png"


### The main menu
[[menu.main]]
  name = "Blog"
  weight = 99
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "What's my IP?"
  weight = 100
  url = "https://ip.1a4.fr/"

[[menu.main]]
  name = "Encrypted Pastebin"
  weight = 101
  url = "https://1a4.fr/"
