# Top-level site settings
baseurl = "https://lamendola.me"
builddrafts = false
author = "Salvatore LaMendola"
languageCode = "en-us"
title = "Sitevatore"
theme = "cocoavatore"
disablePathToLower = true
#googleAnalytics = "" ### No thanks.
#disqusShortname = "blogvatore" ### Too slow

[permalinks]
  blog = "blog/:slug/"

[blackfriday]
  #plainIDAnchors = true
  hrefTargetBlank = true

[params]
  #twitter = "https://twitter.com/yourtwitterusername"
  include_rss = true           # include RSS <link> tag in <head> and show RSS icon
  latestpostscount = 5              # how many posts to display on the home page
  i18n_flags = false # whether to display small country flags for available translations
  author = "SALVATORE LAMENDOLA (vt0r)"
  cachebuster = false # add the current unix timestamp in query string for cache busting css assets
  dateform = "Jan 2, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 MST"
  #description = ""
  email = "salvatore[at@@]lamendola[dot..]me"
  #extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.
  faviconfile = "images/favicon.ico"
  github = "https://github.com/vt0r"
  #instagram = "//instagram.com/you"
  #px500 = "//500px.com/username"
  lang = "en"
  linkedin = "https://www.linkedin.com/in/salvatorelamendola"
  keybase = "https://keybase.io/vt0r"
  noshowreadtime = false # if true, don't show "<x> minutes read" in posts
  selfintro = "" # appears in the site header when set to a non-empty string
  highlightjs = true
  # highlightjslanguages = ["go"] # additional languages not included in the "common" set
  highlightjsStyle = "solarized-dark"
  avatar = "images/avatar@2x.png"


### The main menu
[[menu.main]]
  name = "Blog"
  weight = 99
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "What's my IP?"
  weight = 100
  url = "https://ip.lamendola.me/"

[[menu.main]]
  name = "Encrypted Pastebin"
  weight = 101
  url = "https://1a4.fr/"
